[build]
builder = "nixpacks"
buildCommand = "chmod +x build.sh && ./build.sh"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/admin/login/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[volumes]
media = "/media"
