[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y imagemagick && chmod +x build.sh && ./build.sh"

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
healthcheckPath = "/admin/login/"
healthcheckTimeout = 300  # Increased timeout to 5 minutes
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[[ports]]
port = 8000
protocol = "tcp"

[volumes]
media = "/media"
