services:
  # A Django web service
  - type: web
    name: gcda-web
    env: python
    buildCommand: sh ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: gcda_db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1
    # Configure proper permissions for static and media files
    postBuild:
      command: chmod -R 755 staticfiles && chmod -R 755 /opt/render/project/src/media

# Configure disk for media storage
disks:
  - name: media
    mountPath: /opt/render/project/src/media
    sizeGB: 1

# Simplify static path handling
staticPublishPath: "./staticfiles"

databases:
  - name: gcda_db
    databaseName: gcda
    user: gcda
    plan: free
