services:
  # A Django web service
  - type: web
    name: gcda-web
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: gcda_db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1

databases:
  - name: gcda_db
    databaseName: gcda
    user: gcda
    plan: free
