services:
  # A Django web service
  - type: web
    name: gcda-web
    env: python
    buildCommand: sh ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: gcda_db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12
    # Add this post-build command to ensure proper static file handling
    postBuild:
      command: chmod -R 755 staticfiles

# Simplify static path handling
staticPublishPath: "./staticfiles"

databases:
  - name: gcda_db
    databaseName: gcda
    user: gcda
    plan: free
