# Generated by Django 4.2.20 on 2025-04-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='news_pages', to='news.newscategory'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='intro',
            field=models.CharField(help_text='Brief introduction', max_length=250),
        ),
    ]
