# Generated by Django 4.2.20 on 2025-04-16 00:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('mission_statement', wagtail.fields.RichTextField(blank=True)),
                ('hero_subtitle', wagtail.fields.RichTextField(blank=True)),
                ('hero_cta_text', models.CharField(blank=True, max_length=50)),
                ('hero_video_url', models.URLField(blank=True)),
                ('about_title', models.CharField(blank=True, max_length=100)),
                ('about_subtitle', models.CharField(blank=True, max_length=100)),
                ('about_description', wagtail.fields.RichTextField(blank=True)),
                ('about_content_secondary', wagtail.fields.RichTextField(blank=True)),
                ('about_cta_text', models.CharField(blank=True, max_length=50)),
                ('about_cta_link', models.URLField(blank=True)),
                ('services_title', models.CharField(blank=True, max_length=100)),
                ('services_subtitle', models.CharField(blank=True, max_length=100)),
                ('services_description', wagtail.fields.RichTextField(blank=True)),
                ('team_title', models.CharField(blank=True, max_length=100)),
                ('team_subtitle', models.CharField(blank=True, max_length=100)),
                ('team_description', wagtail.fields.RichTextField(blank=True)),
                ('contact_title', models.CharField(blank=True, max_length=100)),
                ('contact_subtitle', models.CharField(blank=True, max_length=100)),
                ('contact_description', wagtail.fields.RichTextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('people_helped', models.IntegerField(default=0)),
                ('countries_served', models.IntegerField(default=0)),
                ('projects_completed', models.IntegerField(default=0)),
                ('volunteers', models.IntegerField(default=0)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Homepage',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TeamMemberOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', wagtail.fields.RichTextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.homepage')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', wagtail.fields.RichTextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class name', max_length=50)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedProgramOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', wagtail.fields.RichTextField()),
                ('link', models.URLField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_programs', to='core.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
